#version 450 core

layout (local_size_x = 16, local_size_y = 1, local_size_z = 1) in;

layout (set = 1, binding = 0) buffer InputBuffer
{
    mat4 matrix1;
    mat4 matrix2;
    mat4 matrix3;
};

layout (set = 1, binding = 1) buffer OutputBuffer
{
    mat4 matrix4;
};

void main()
{
    int index = int(gl_GlobalInvocationID.x);
    matrix4[index] += matrix1[index] + matrix2[index] + matrix3[index];
}